config/routes.rb
Jalkaennustus::Application.routes.draw do
  devise_for :groups

   resources :tournaments do
     resources :users do
       resources :games
       resources :user_questions
     end
   end
      
   match 'tournaments/:tournament_id/users/:user_id/teams/group' => "teams#group", :as => 'group_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/group' => "teams#createGroup", :as => 'group_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/quarterfinals' => "teams#quarterfinals", :as => 'quarterfinals_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/quarterfinals' => "teams#createQuarterfinals", :as => 'quarterfinals_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/round_of_16' => "teams#roundOf16", :as => 'round_of_16_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/round_of_16' => "teams#createRoundOf16", :as => 'round_of_16_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/finals' => "teams#finals", :as => 'finals_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/finals' => "teams#createFinals", :as => 'finals_teams', :via => :post

  root :to => 'tournaments#index'

end

app/models/user_question.rb
class UserQuestion < ActiveRecord::Base
  
  attr_accessible :user_id, :question_id, :answer, :tournament_id
  
end

app/controllers/user_questions_controller.rb
class UserQuestionsController < ApplicationController
  
  def index
    @tournament_id = params[:tournament_id]
    @user = User.find_by_id params[:user_id]
    @questions = Question.all
    @user_questions = UserQuestion.find_all_by_user_id_and_tournament_id @user.id, @tournament_id
  end

  def create
    tournament_id = params[:tournament_id]
    user_id = params[:user_id]    
    user = User.find_by_id user_id
=begin
    if user.name != 'tegelikud tulemused'
      raise "Mine pekki!"
    end
=end
    
    existing_user_questions = UserQuestion.find_all_by_user_id_and_tournament_id user_id, tournament_id
    answers = params[:answers]
    
    answers.map do |k,v|
      existing_user_question = existing_user_questions == nil ? nil : existing_user_questions.select{|q| k.to_i == q.question_id}
      if existing_user_question == nil || existing_user_question.empty?
        UserQuestion.create!(:user_id => user_id, :question_id => k, :answer => v, :tournament_id => tournament_id)
      else
        user_question = existing_user_question[0]
        user_question.update_attribute(:answer, v)
      end
    end
    if user.name == 'tegelikud tulemused'
      User.calculate_points tournament_id, current_group
    end
    redirect_to tournament_user_path(tournament_id, user_id)
  end
  
end

app/views/user_questions/index.html.haml
%h2 Vasta järgmistele lisaküsimustele:

= form_tag tournament_user_user_questions_path(@tournament_id, @user.id), :method => :post do
  - @questions.each do |question|
    = "#{question.question}"
    %br
    %br
    Vastus: 
    = text_field :answers, "#{question.id}", :value => "#{@user_questions == nil || @user_questions.empty? ? nil : @user_questions.select{|uq| question.id == uq.question_id}[0].answer}"
    %br
    %br
    %br
  * Õiged vastused küsimustele 1, 2 ja 4 annavad igaüks 10 punkti. Küsimused 3 ja 5 annavad maksimaalselt 10 punkti, sellest lahutatakse arv mille võrra vastus erineb õigest vastusest. 5. küsimuse eest saab punkte vaid juhul kui 4. küsimus on õigesti vastatud.
  %br
  %br
  = hidden_field_tag "user_id", @user.id
  = hidden_field_tag "tournament_id", @tournament_id
  -#- if @user.name == 'tegelikud tulemused'
  -#  = submit_tag 'Salvesta', :class => 'form_btn'
  = submit_tag 'Salvesta', :class => 'form_btn'
= button_to 'Tagasi', tournament_user_path(@tournament_id, @user.id), :method => :get, :class => 'form_btn'