config/routes.rb
Jalkaennustus::Application.routes.draw do
  devise_for :groups

   resources :tournaments do
     resources :users do
       resources :games
       resources :user_questions
     end
   end
      
   match 'tournaments/:tournament_id/users/:user_id/teams/group' => "teams#group", :as => 'group_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/group' => "teams#createGroup", :as => 'group_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/quarterfinals' => "teams#quarterfinals", :as => 'quarterfinals_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/quarterfinals' => "teams#createQuarterfinals", :as => 'quarterfinals_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/round_of_16' => "teams#roundOf16", :as => 'round_of_16_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/round_of_16' => "teams#createRoundOf16", :as => 'round_of_16_teams', :via => :post
   
   match 'tournaments/:tournament_id/users/:user_id/teams/finals' => "teams#finals", :as => 'finals_teams', :via => :get
   match 'tournaments/:tournament_id/users/:user_id/teams/finals' => "teams#createFinals", :as => 'finals_teams', :via => :post

  root :to => 'tournaments#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  
  attr_accessible :id, :team1_id, :team2_id, :group, :double_points, :tournament_id
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    user_id = params[:user_id]
    @tournament_id = params[:tournament_id]
    @user = User.find_by_id user_id
    @userGames = UserGame.where(:user_id => user_id, :tournament_id => @tournament_id)
    @games = Game.where(:tournament_id => @tournament_id).order('id')
    @teams = Team.find_all_by_tournament_id @tournament_id
  end
  
  def show
    @user_id = params[:user_id]
    @tournament_id = params[:tournament_id]
    game_id = params[:id]
    @userGames = VUserGames.find_by_game_and_group game_id, current_group.id
  end

  def create
    result = params[:result]
    user_id = params[:user_id]
    tournament_id = params[:tournament_id]
    user = User.find_by_id user_id
=begin
    if user.name != 'tegelikud tulemused'
      raise "Mine pekki!"
    end
=end
    userGames = UserGame.where(:user_id => user_id, :tournament_id => tournament_id)
    result.map do |k,v|
      existingGames = userGames == nil ? nil : userGames.select{|userGame| k.to_i == userGame.game_id}
      if (existingGames == nil || existingGames.empty?) && (v != nil && !v.empty?)
        UserGame.create!(:user_id => user_id, :game_id => k, :result => v, :tournament_id => tournament_id)
      elsif existingGames != nil && !existingGames.empty?
        existingGame = existingGames[0]
        existingGame.update_attribute(:result, v)
      end
    end
    if user.name == 'tegelikud tulemused'
      User.calculate_points tournament_id, current_group
    end
    redirect_to tournament_user_path(tournament_id, user_id)
  end
  
end

app/views/games/index.html.haml
%h2 Ennusta alagrupimängude tulemused

= form_tag tournament_user_games_path(@tournament_id, @user.id), :method => :post do
  %table#users
    %thead
      %tr
        %th Alagrupp
        %th Mäng
        %th Tulemus
        %th
    %tbody
      - @games.each do |game|
        = fields_for :game, game do |g|
          %tr
            %td{:class => "#{game.double_points == 1 ? 'bold' : ''}"}= game.group
            %td{:class => "#{game.double_points == 1 ? 'bold' : ''}"}= "#{@teams.select{|team| team.id == game.team1_id}[0].name} - #{@teams.select{|team| team.id == game.team2_id}[0].name}"
            %td= select :result, "#{game.id}",
              [["#{@teams.select{|team| team.id == game.team1_id}[0].name} võidab kuni kahe väravaga",'1A'],
              ["#{@teams.select{|team| team.id == game.team1_id}[0].name} võidab vähemalt kolme väravaga",'1B'],
              ["#{@teams.select{|team| team.id == game.team2_id}[0].name} võidab kuni kahe väravaga",'2A'],
              ["#{@teams.select{|team| team.id == game.team2_id}[0].name} võidab vähemalt kolme väravaga",'2B'],
              ['Mäng lõppeb viigiga','X']], 
              {:selected => "#{@userGames == nil || @userGames.empty? || @userGames.select{|userGame| game.id == userGame.game_id}.empty? ? '' : @userGames.select{|userGame| game.id == userGame.game_id}[0].result}", 
               :prompt => '- vali -'}, 
               {:class=>"games"}
            %td= link_to 'Vaata teiste ennustusi', tournament_user_game_path(@tournament_id, @user.id, game.id)
  * Õige vastus annab 5 punkti. Õige võitja aga vale vastus annab 3 punkti. Boldiga tähistatud mängude ennustamine annab topeltpunktid.
  %br
  %br
  = hidden_field_tag "user_id", @user.id
  = hidden_field_tag "tournament_id", @tournament_id
  -#- if @user.name == 'tegelikud tulemused'
  -#  = submit_tag 'Salvesta'
  = submit_tag 'Salvesta', :class => 'form_btn'
= button_to 'Tagasi', tournament_user_path(@tournament_id, @user.id), :method => :get, :class => 'form_btn'

app/views/games/show.html.haml
%h2 Ennustused

%table#games
  %thead
    %tr
      %th Nimi
      %th Tulemus
  %tbody
    - @userGames.each do |userGame|
      %tr
        %td= userGame.user_name
        %td= userGame.get_result_text
= button_to 'Tagasi', tournament_user_games_path(@tournament_id, @user_id), :method => :get, :class => 'form_btn'